version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          command: sudo npm i -g serverless yarn@latest
      - run:
          command: yarn install
      - run:
          command: ./.circleci/install-credentials.sh
      - run:
          command: yarn test

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
          context: graphqlSlsTsWisemuffin
          filters:
            branches:
              only:
                - master
